name: Smart Random Commits

on:
  schedule:
    - cron: "30 2 * * *"  # Run daily at 8:00 AM IST
  workflow_dispatch:

jobs:
  random-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Make random commits
        run: |
          # Random chance to skip today
          if [ $((RANDOM % 2)) -eq 0 ]; then
            echo "Skipping commit today"
            exit 0
          fi

          # Decide number of commits today (1 to 3)
          COUNT=$(( (RANDOM % 3) + 1 ))
          echo "Making $COUNT commits today"

          git config --global user.name "Dixit Kumar"
          git config --global user.email "dixitkhanda1@gmail.com"

          for ((i=1; i<=COUNT; i++))
          do
            echo "// Random commit $i on $(date)" >> hello.cpp
            git add hello.cpp
            git commit -m "Random commit $i on $(date)"
          done

          git push
